### ISSUE TITLE
Exit with non-zero in case of failure

### ISSUE THREAD

**Issue by AlexanderYastrebov** [kelseyhightower/echo#5]
Command should return non zero code in case of failure

From HN comment:
``
touch foo.txt; chmod 400 foo.txt; echo ouch > foo.txt; echo $?
``

**Comment by Rotsor** [comment]
The script above does print an error message and `echo` command doesn't even run because bash fails to open the file. You need something else, e.g. `touch bar.txt; ./echo hi 1<bar.txt; echo $?`.
